export const articleSources = [
  {"id": "editorial-3194de4412b004", "title": "Anchor It campaign", "organization": "www.anchorit.gov", "url": "https://www.anchorit.gov/"},
  {"id": "editorial-71aeb0bf1cd395", "title": "CPSC childproofing guide", "organization": "www.cpsc.gov", "url": "https://www.cpsc.gov/safety-education/safety-guides/kids-and-babies/Childproofing-Your-Home"},
  {"id": "editorial-8bcba0bcb86eea", "title": "CPSC safe-sleep guidance", "organization": "www.cpsc.gov", "url": "https://www.cpsc.gov/SafeSleep"},
  {"id": "editorial-34675dd6c49a1b", "title": "crib standards history", "organization": "www.cpsc.gov", "url": "https://www.cpsc.gov/Regulations-Laws--Standards/Voluntary-Standards/Cribs"},
  {"id": "editorial-b66a4ddc9ba5ea", "title": "CPSC product registration guidance", "organization": "www.cpsc.gov", "url": "https://www.cpsc.gov/Business--Manufacturing/Business-Education/FAQ?p=3019&tid%5B3029%5D=3029"},
  {"id": "editorial-2fb2c0c5728606", "title": "HealthyChildren safety and prevention", "organization": "www.healthychildren.org", "url": "https://www.healthychildren.org/English/safety-prevention/Pages/default.aspx"},
  {"id": "editorial-42e3b620227cca", "title": "CPSC safety education", "organization": "www.cpsc.gov", "url": "https://www.cpsc.gov/Safety-Education"},
  {"id": "editorial-01bc305d67e1be", "title": "CPSC recalls database", "organization": "www.cpsc.gov", "url": "https://www.cpsc.gov/Recalls"},
  {"id": "editorial-363b84bc774875", "title": "CPSC guidance for suspected swallowing", "organization": "www.cpsc.gov", "url": "https://www.cpsc.gov/Safety-Education/Safety-Education-Centers/Magnets"},
  {
    id: "cpsc-childproofing",
    title: "Childproofing Your Home",
    organization: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/safety-education/safety-guides/kids-and-babies/Childproofing-Your-Home",
  },
  {
    id: "cpsc-child-safety",
    title: "Child Safety",
    organization: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/safety-education/neighborhood-safety-network/toolkits/child-safety",
  },
  {
    id: "cpsc-recalls",
    title: "Recalls and Product Safety Warnings",
    organization: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/Recalls",
  },
  {
    id: "safer-products",
    title: "SaferProducts.gov",
    organization: "U.S. Consumer Product Safety Commission",
    url: "https://www.saferproducts.gov/",
  },
  {
    id: "aap-safe-sleep",
    title: "Safe Sleep",
    organization: "American Academy of Pediatrics",
    url: "https://www.aap.org/en/patient-care/safe-sleep/",
  },
  {
    id: "healthychildren-safe-sleep",
    title: "How to Keep Your Sleeping Baby Safe",
    organization: "HealthyChildren.org",
    url: "https://www.healthychildren.org/English/ages-stages/baby/sleep/Pages/a-parents-guide-to-safe-sleep.aspx",
  },
  {
    id: "nhtsa-car-seats",
    title: "Car Seats and Booster Seats",
    organization: "National Highway Traffic Safety Administration",
    url: "https://www.nhtsa.gov/vehicle-safety/car-seats-and-booster-seats",
  },
  {
    id: "nhtsa-car-seat-finder",
    title: "Find the Right Car Seat",
    organization: "National Highway Traffic Safety Administration",
    url: "https://www.nhtsa.gov/campaign/right-seat",
  },
  {
    id: "nhtsa-ease-of-use",
    title: "Car Seat Ease-of-Use Ratings",
    organization: "National Highway Traffic Safety Administration",
    url: "https://www.nhtsa.gov/car-seats-and-booster-seats/car-seat-ease-use-ratings",
  },
  {
    id: "healthychildren-stroller",
    title: "How to Choose a Safe Baby Stroller",
    organization: "HealthyChildren.org",
    url: "https://www.healthychildren.org/English/safety-prevention/on-the-go/Pages/How-to-Buy-a-Safe-Stroller.aspx",
  },
  {
    id: "healthychildren-travel",
    title: "Flying With Baby: Parent FAQs & Tips for Safer, Easier Air Travel",
    organization: "HealthyChildren.org",
    url: "https://www.healthychildren.org/English/safety-prevention/on-the-go/Pages/Flying-with-Baby.aspx",
  },
  {
    id: "cpsc-small-parts",
    title: "Small Parts and Choking Hazard Labeling FAQs",
    organization: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/FAQ/Small-Parts-and-Choking-Hazard-Labeling-FAQs",
  },
  {
    id: "cpsc-toy-safety",
    title: "Toy Safety Business Guidance",
    organization: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/Business--Manufacturing/Business-Education/Toy-Safety",
  },
  {
    id: "cpsc-anchor-it",
    title: "Anchor It",
    organization: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/Safety-Education/Safety-Education-Centers/AnchorItgov",
  },
  {
    id: "cpsc-bike-helmets",
    title: "Bicycle Helmets Business Guidance",
    organization: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/Business--Manufacturing/Business-Education/Business-Guidance/Bicycle-Helmets",
  },
];
